version: '3.8'

services:
  api:
    build: .
    image: wisrovi/analize_code_quality:v1.0
    ports:
      - "8032:8000"
    # volumes:
    #   - .:/app
    # command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    # command: tail -f /dev/null
    # command: ./start.sh